name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout the repository
        uses: actions/checkout@v4
      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHTOKEN }}
      - 
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest 
          labels: |
            repo=${{ github.repository }}
            commit=${{ github.sha }}
            branch=${{ github.ref_name }}
  

