name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  login-ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHTOKEN }}

  build-publish-ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Build the Docker image
        uses: actions/checkout@v4
      - run: |
          docker build . -t ghcr.io/magedragheb/weatherapi:latest
          docker push ghcr.io/magedragheb/weatherapi:latest
