name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build-publish-ghcr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: | 
        docker login --username magedragheb --password-stdin ${{ secrets.GHTOKEN }}
        docker build . --tag ghcr.io/magedragheb/weatherapi:latest
        docker push ghcr.io/magedragheb/weatherapi:latest

