name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build-publish-ghcr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          echo ${{secrets.GHTOKEN}} | docker login ghcr.io -u magedragheb --password-stdin
          docker build . -t ghcr.io/magedragheb/weatherapi:latest
          docker push ghcr.io/magedragheb/weatherapi:latest
