name: Trigger auto deployment for noapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/noapp-AutoDeployTrigger-b9b1d0d3-3c05-4006-902c-c6d55bbefde3.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.NOAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.NOAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.NOAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.NOAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.NOAPP_REGISTRY_PASSWORD }}
          containerAppName: noapp
          resourceGroup: CourseEngineTesting
          imageToBuild: ghcr.io/noapp:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


